# Generated by Django 5.1.6 on 2025-03-07 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location_details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValueAdditionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('guide', models.TextField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('time_required', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_needed', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tips', models.TextField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.valueadditionmethod')),
            ],
        ),
        migrations.CreateModel(
            name='MethodSellingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.sellingplace')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.valueadditionmethod')),
            ],
        ),
        migrations.CreateModel(
            name='MethodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ingredient')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.valueadditionmethod')),
            ],
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_analysis', models.TextField()),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.valueadditionmethod')),
            ],
        ),
    ]
