# Generated by Django 5.1.6 on 2025-03-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valueadditionmethod',
            name='category',
            field=models.CharField(choices=[('snacks', 'Snacks'), ('beverages', 'Beverages'), ('baking', 'Baking'), ('animal_feed', 'Animal Feed'), ('fertilizer', 'Fertilizer'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='valueadditionmethod',
            name='ripeness_stage',
            field=models.CharField(choices=[('unripe', 'Unripe'), ('ripe', 'Ripe'), ('overripe', 'Overripe'), ('rotten', 'Rotten')], default='ripe', max_length=20),
        ),
    ]
