name: Fullstack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      python-version: '3.10'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install All Dependencies
        run: |
          pip install -r requirements.txt

  backend:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Django Migrations
        run: |
          python manage.py migrate

      - name: Run Backend Tests
        run: |
          python manage.py test

  model:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Train YOLOv8 Model (Optional)
        run: |
          python api

      - name: Run Inference Tests
        run: |
          python api
